version: 3.8

services:
  backend:
    build:
      context:
        dockerfile : dockerfile
    container_name: document-backend
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      Spring_Datasource_url: jdbc:postgresql://localhost:5432/DocManagement
      Spring_Datasource_username: rachit1997
      Spring_Datasource_password: rachit1997
